// <auto-generated />
using System;
using Backend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016012522_AddEntidadAndActXEntidad")]
    partial class AddEntidadAndActXEntidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Domain.ActXEntidad", b =>
                {
                    b.Property<int>("ActXEntidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActXEntidadId"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<decimal>("Efectivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<decimal>("Especie")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ActXEntidadId");

                    b.HasIndex("ActividadId");

                    b.HasIndex("EntidadId");

                    b.ToTable("ActXEntidades");
                });

            modelBuilder.Entity("Backend.Models.Domain.Actividad", b =>
                {
                    b.Property<int>("ActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActividadId"));

                    b.Property<int>("CantidadAnios")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspecificacionesTecnicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ActividadId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("Backend.Models.Domain.CapacitacionEventos", b =>
                {
                    b.Property<int>("CapacitacionEventosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapacitacionEventosId"));

                    b.Property<int?>("ActividadId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PeriodoNum")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CapacitacionEventosId");

                    b.HasIndex("ActividadId");

                    b.ToTable("CapacitacionEventos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Entidad", b =>
                {
                    b.Property<int>("EntidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntidadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntidadId");

                    b.ToTable("Entidad");
                });

            modelBuilder.Entity("Backend.Models.Domain.EquiposSoftware", b =>
                {
                    b.Property<int>("EquiposSoftwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquiposSoftwareId"));

                    b.Property<int?>("ActividadId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("EspecificacionesTecnicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoNum")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EquiposSoftwareId");

                    b.HasIndex("ActividadId");

                    b.ToTable("EquiposSoftware");
                });

            modelBuilder.Entity("Backend.Models.Domain.GastosViaje", b =>
                {
                    b.Property<int>("GastosViajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastosViajeId"));

                    b.Property<int?>("ActividadId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodoNum")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.HasKey("GastosViajeId");

                    b.HasIndex("ActividadId");

                    b.ToTable("GastosViaje");
                });

            modelBuilder.Entity("Backend.Models.Domain.MaterialesInsumos", b =>
                {
                    b.Property<int>("MaterialesInsumosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialesInsumosId"));

                    b.Property<int?>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Materiales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoNum")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialesInsumosId");

                    b.HasIndex("ActividadId");

                    b.ToTable("MaterialesInsumos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 590, DateTimeKind.Utc).AddTicks(4579),
                            Description = "Rol con permisos completos del sistema",
                            IsActive = true,
                            Name = "Administrador",
                            Permissions = "[\"users.create\", \"users.read\", \"users.update\", \"users.delete\", \"weather.create\", \"weather.read\", \"weather.update\", \"weather.delete\"]"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 590, DateTimeKind.Utc).AddTicks(4585),
                            Description = "Rol con permisos básicos del sistema",
                            IsActive = true,
                            Name = "Usuario",
                            Permissions = "[\"users.read\", \"weather.read\"]"
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.Rubro", b =>
                {
                    b.Property<int>("RubroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubroId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RubroId");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("Backend.Models.Domain.ServiciosTecnologicos", b =>
                {
                    b.Property<int>("ServiciosTecnologicosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiciosTecnologicosId"));

                    b.Property<int?>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoNum")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServiciosTecnologicosId");

                    b.HasIndex("ActividadId");

                    b.ToTable("ServiciosTecnologicos");
                });

            modelBuilder.Entity("Backend.Models.Domain.TalentoHumano", b =>
                {
                    b.Property<int>("TalentoHumanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalentoHumanoId"));

                    b.Property<int?>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("CargoEspecifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoNum")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<int>("Semanas")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TalentoHumanoId");

                    b.HasIndex("ActividadId");

                    b.ToTable("TalentoHumano");
                });

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("local");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 715, DateTimeKind.Utc).AddTicks(2569),
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            IsActive = true,
                            LastName = "Pérez",
                            PasswordHash = "$2a$11$CpDuebgC7CL7gqNqc.N0XO3qEOvC3GWH7Q/7w9K65Yk42l9TT/5LC",
                            Provider = "local",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 840, DateTimeKind.Utc).AddTicks(6675),
                            Email = "maria.gonzalez@email.com",
                            FirstName = "María",
                            IsActive = true,
                            LastName = "González",
                            PasswordHash = "$2a$11$YzCmqmPuq4hmsofPZaV0o.iIiGXFv8.Q.O56Cg1n80UsCx.TxjtyC",
                            Provider = "local",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(2975),
                            Email = "carlos.lopez@email.com",
                            FirstName = "Carlos",
                            IsActive = false,
                            LastName = "López",
                            PasswordHash = "$2a$11$W/ZEyoh9LKd3MF1lcj1JWOMLwKcZEsyigWr4ieeuQAJPIY34NUAkW",
                            Provider = "local",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3399),
                            Date = new DateOnly(2025, 10, 16),
                            Summary = "Bracing",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3413),
                            Date = new DateOnly(2025, 10, 17),
                            Summary = "Warm",
                            TemperatureC = -11
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3415),
                            Date = new DateOnly(2025, 10, 18),
                            Summary = "Chilly",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3416),
                            Date = new DateOnly(2025, 10, 19),
                            Summary = "Warm",
                            TemperatureC = 34
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3417),
                            Date = new DateOnly(2025, 10, 20),
                            Summary = "Hot",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3427),
                            Date = new DateOnly(2025, 10, 21),
                            Summary = "Chilly",
                            TemperatureC = -3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3428),
                            Date = new DateOnly(2025, 10, 22),
                            Summary = "Cool",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3429),
                            Date = new DateOnly(2025, 10, 23),
                            Summary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3430),
                            Date = new DateOnly(2025, 10, 24),
                            Summary = "Freezing",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 16, 1, 25, 21, 964, DateTimeKind.Utc).AddTicks(3432),
                            Date = new DateOnly(2025, 10, 25),
                            Summary = "Warm",
                            TemperatureC = 41
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.ActXEntidad", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", "Actividad")
                        .WithMany("ActXEntidades")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Domain.Entidad", "Entidad")
                        .WithMany("ActXEntidades")
                        .HasForeignKey("EntidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("Backend.Models.Domain.CapacitacionEventos", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", "Actividad")
                        .WithMany("CapacitacionEventos")
                        .HasForeignKey("ActividadId");

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("Backend.Models.Domain.EquiposSoftware", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", null)
                        .WithMany("EquiposSoftware")
                        .HasForeignKey("ActividadId");
                });

            modelBuilder.Entity("Backend.Models.Domain.GastosViaje", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", "Actividad")
                        .WithMany("GastosViaje")
                        .HasForeignKey("ActividadId");

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("Backend.Models.Domain.MaterialesInsumos", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", "Actividad")
                        .WithMany("MaterialesInsumos")
                        .HasForeignKey("ActividadId");

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("Backend.Models.Domain.ServiciosTecnologicos", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", null)
                        .WithMany("ServiciosTecnologicos")
                        .HasForeignKey("ActividadId");
                });

            modelBuilder.Entity("Backend.Models.Domain.TalentoHumano", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", "Actividad")
                        .WithMany("TalentoHumano")
                        .HasForeignKey("ActividadId");

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.HasOne("Backend.Models.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Domain.Actividad", b =>
                {
                    b.Navigation("ActXEntidades");

                    b.Navigation("CapacitacionEventos");

                    b.Navigation("EquiposSoftware");

                    b.Navigation("GastosViaje");

                    b.Navigation("MaterialesInsumos");

                    b.Navigation("ServiciosTecnologicos");

                    b.Navigation("TalentoHumano");
                });

            modelBuilder.Entity("Backend.Models.Domain.Entidad", b =>
                {
                    b.Navigation("ActXEntidades");
                });

            modelBuilder.Entity("Backend.Models.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
