// <auto-generated />
using System;
using Backend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250925054045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(1420),
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            IsActive = true,
                            LastName = "Pérez"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(1426),
                            Email = "maria.gonzalez@email.com",
                            FirstName = "María",
                            IsActive = true,
                            LastName = "González"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(1429),
                            Email = "carlos.lopez@email.com",
                            FirstName = "Carlos",
                            IsActive = false,
                            LastName = "López"
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2054),
                            Date = new DateOnly(2025, 9, 26),
                            Summary = "Bracing",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2066),
                            Date = new DateOnly(2025, 9, 27),
                            Summary = "Warm",
                            TemperatureC = -11
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2069),
                            Date = new DateOnly(2025, 9, 28),
                            Summary = "Chilly",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2072),
                            Date = new DateOnly(2025, 9, 29),
                            Summary = "Warm",
                            TemperatureC = 34
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2075),
                            Date = new DateOnly(2025, 9, 30),
                            Summary = "Hot",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2084),
                            Date = new DateOnly(2025, 10, 1),
                            Summary = "Chilly",
                            TemperatureC = -3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2087),
                            Date = new DateOnly(2025, 10, 2),
                            Summary = "Cool",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2090),
                            Date = new DateOnly(2025, 10, 3),
                            Summary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2093),
                            Date = new DateOnly(2025, 10, 4),
                            Summary = "Freezing",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 25, 5, 40, 43, 805, DateTimeKind.Utc).AddTicks(2098),
                            Date = new DateOnly(2025, 10, 5),
                            Summary = "Warm",
                            TemperatureC = 41
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
