// <auto-generated />
using System;
using Backend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002214006_AddRolesAndPasswordHash")]
    partial class AddRolesAndPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 4, 512, DateTimeKind.Utc).AddTicks(9767),
                            Description = "Rol con permisos completos del sistema",
                            IsActive = true,
                            Name = "Administrador",
                            Permissions = "[\"users.create\", \"users.read\", \"users.update\", \"users.delete\", \"weather.create\", \"weather.read\", \"weather.update\", \"weather.delete\"]"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 4, 512, DateTimeKind.Utc).AddTicks(9782),
                            Description = "Rol con permisos básicos del sistema",
                            IsActive = true,
                            Name = "Usuario",
                            Permissions = "[\"users.read\", \"weather.read\"]"
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 4, 831, DateTimeKind.Utc).AddTicks(9716),
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            IsActive = true,
                            LastName = "Pérez",
                            PasswordHash = "$2a$11$z.mS7rxE2lXTZa/FLBRZQ.Mjb0ApUDKiZvGyRQzMwvjQQO/zZf4CC",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 185, DateTimeKind.Utc).AddTicks(7445),
                            Email = "maria.gonzalez@email.com",
                            FirstName = "María",
                            IsActive = true,
                            LastName = "González",
                            PasswordHash = "$2a$11$xL.4FeqN2HV.2tvvAcERY./i/GL3XDUQ7.LNAWJzRkFaWuMfrPLSK",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(6474),
                            Email = "carlos.lopez@email.com",
                            FirstName = "Carlos",
                            IsActive = false,
                            LastName = "López",
                            PasswordHash = "$2a$11$oAqO/zHXCIpmBrf.BmT3HuqNpfIPWfI03DmReZhYCBuS4HZG5HF4i",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7349),
                            Date = new DateOnly(2025, 10, 3),
                            Summary = "Bracing",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7377),
                            Date = new DateOnly(2025, 10, 4),
                            Summary = "Warm",
                            TemperatureC = -11
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7382),
                            Date = new DateOnly(2025, 10, 5),
                            Summary = "Chilly",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7387),
                            Date = new DateOnly(2025, 10, 6),
                            Summary = "Warm",
                            TemperatureC = 34
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7391),
                            Date = new DateOnly(2025, 10, 7),
                            Summary = "Hot",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7412),
                            Date = new DateOnly(2025, 10, 8),
                            Summary = "Chilly",
                            TemperatureC = -3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7417),
                            Date = new DateOnly(2025, 10, 9),
                            Summary = "Cool",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7489),
                            Date = new DateOnly(2025, 10, 10),
                            Summary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7494),
                            Date = new DateOnly(2025, 10, 11),
                            Summary = "Freezing",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 2, 21, 40, 5, 545, DateTimeKind.Utc).AddTicks(7503),
                            Date = new DateOnly(2025, 10, 12),
                            Summary = "Warm",
                            TemperatureC = 41
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.HasOne("Backend.Models.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
