// <auto-generated />
using System;
using Backend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Domain.ActXEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<decimal>("Efectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<decimal>("Especie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalContribucion")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("EntidadId");

                    b.ToTable("ActXEntidades");
                });

            modelBuilder.Entity("Backend.Models.Domain.Actividad", b =>
                {
                    b.Property<int>("ActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActividadId"));

                    b.Property<int>("CadenaDeValorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionAnios")
                        .HasColumnType("int");

                    b.Property<string>("EspecificacionesTecnicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ActividadId");

                    b.HasIndex("CadenaDeValorId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("Backend.Models.Domain.Administrativos", b =>
                {
                    b.Property<int>("AdministrativoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdministrativoId"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("AdministrativoId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("Administrativos");
                });

            modelBuilder.Entity("Backend.Models.Domain.CadenaDeValor", b =>
                {
                    b.Property<int>("CadenaDeValorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CadenaDeValorId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivoEspecifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("int");

                    b.HasKey("CadenaDeValorId");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("CadenasDeValor");
                });

            modelBuilder.Entity("Backend.Models.Domain.CapacitacionEventos", b =>
                {
                    b.Property<int>("CapacitacionEventosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapacitacionEventosId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CapacitacionEventosId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("CapacitacionEventos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Contratacion", b =>
                {
                    b.Property<int>("ContratacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContratacionId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienciaMinima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentidadAcademica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NivelGestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorMensual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ContratacionId");

                    b.ToTable("Contrataciones");
                });

            modelBuilder.Entity("Backend.Models.Domain.CronogramaTarea", b =>
                {
                    b.Property<int>("CronogramaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CronogramaId"));

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMeses")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.HasKey("CronogramaId");

                    b.HasIndex("TareaId");

                    b.ToTable("CronogramaTareas");
                });

            modelBuilder.Entity("Backend.Models.Domain.Divulgacion", b =>
                {
                    b.Property<int>("DivulgacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivulgacionId"));

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedioDivulgacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("DivulgacionId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("Divulgacion");
                });

            modelBuilder.Entity("Backend.Models.Domain.Entidad", b =>
                {
                    b.Property<int>("EntidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntidadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntidadId");

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("Backend.Models.Domain.EquiposSoftware", b =>
                {
                    b.Property<int>("EquiposSoftwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquiposSoftwareId"));

                    b.Property<string>("EspecificacionesTecnicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("EquiposSoftwareId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("EquiposSoftware");
                });

            modelBuilder.Entity("Backend.Models.Domain.GastosViaje", b =>
                {
                    b.Property<int>("GastosViajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastosViajeId"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("GastosViajeId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("GastosViaje");
                });

            modelBuilder.Entity("Backend.Models.Domain.Infraestructura", b =>
                {
                    b.Property<int>("InfraestructuraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfraestructuraId"));

                    b.Property<string>("CaracteristicasTecnicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoInfraestructura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfraestructuraId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("Infraestructura");
                });

            modelBuilder.Entity("Backend.Models.Domain.MaterialesInsumos", b =>
                {
                    b.Property<int>("MaterialesInsumosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialesInsumosId"));

                    b.Property<string>("Materiales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("MaterialesInsumosId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("MaterialesInsumos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Objetivo", b =>
                {
                    b.Property<int>("ObjetivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjetivoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoEsperado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjetivoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Otros", b =>
                {
                    b.Property<int>("OtrosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtrosId"));

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("OtrosId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("Otros");
                });

            modelBuilder.Entity("Backend.Models.Domain.ProteccionConocimientoDivulgacion", b =>
                {
                    b.Property<int>("ProteccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProteccionId"));

                    b.Property<string>("ActividadHapat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadResponsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("ProteccionId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("ProteccionConocimientoDivulgacion");
                });

            modelBuilder.Entity("Backend.Models.Domain.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Recurso", b =>
                {
                    b.Property<int>("RecursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecursoId"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoEspecie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<string>("TipoRecurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecursoId");

                    b.HasIndex("ActividadId");

                    b.HasIndex("EntidadId");

                    b.HasIndex("RubroId");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Backend.Models.Domain.RecursoEspecifico", b =>
                {
                    b.Property<int>("RecursoEspecificoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecursoEspecificoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoNum")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecursoEspecificoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("RecursosEspecificos");
                });

            modelBuilder.Entity("Backend.Models.Domain.RemuneracionPorAnio", b =>
                {
                    b.Property<int>("RemuneracionPorAnioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemuneracionPorAnioId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("Honorarios")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SemanasAnio")
                        .HasColumnType("int");

                    b.Property<int>("TalentoHumanoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAnio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RemuneracionPorAnioId");

                    b.HasIndex("TalentoHumanoId");

                    b.ToTable("RemuneracionesPorAnio");
                });

            modelBuilder.Entity("Backend.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 6, 17, 39, 42, 299, DateTimeKind.Utc).AddTicks(2766),
                            Description = "Rol con permisos completos del sistema",
                            IsActive = true,
                            Name = "Administrador",
                            Permissions = "[\"users.create\", \"users.read\", \"users.update\", \"users.delete\"]"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 6, 17, 39, 42, 299, DateTimeKind.Utc).AddTicks(2770),
                            Description = "Rol con permisos básicos del sistema",
                            IsActive = true,
                            Name = "Usuario",
                            Permissions = "[\"users.read\"]"
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.Rubro", b =>
                {
                    b.Property<int>("RubroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubroId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RubroId");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("Backend.Models.Domain.SeguimientoEvaluacion", b =>
                {
                    b.Property<int>("SeguimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeguimientoId"));

                    b.Property<string>("CargoResponsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodoEvaluacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("SeguimientoId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("SeguimientoEvaluacion");
                });

            modelBuilder.Entity("Backend.Models.Domain.ServiciosTecnologicos", b =>
                {
                    b.Property<int>("ServiciosTecnologicosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiciosTecnologicosId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.HasKey("ServiciosTecnologicosId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("ServiciosTecnologicos");
                });

            modelBuilder.Entity("Backend.Models.Domain.TalentoHumano", b =>
                {
                    b.Property<int>("TalentoHumanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalentoHumanoId"));

                    b.Property<string>("CargoEspecifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContratacionId")
                        .HasColumnType("int");

                    b.Property<int>("RecursoEspecificoId")
                        .HasColumnType("int");

                    b.Property<int>("Semanas")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TalentoHumanoId");

                    b.HasIndex("ContratacionId");

                    b.HasIndex("RecursoEspecificoId")
                        .IsUnique();

                    b.ToTable("TalentoHumano");
                });

            modelBuilder.Entity("Backend.Models.Domain.TalentoHumanoTarea", b =>
                {
                    b.Property<int>("TalentoHumanoTareasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalentoHumanoTareasId"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasAsignadas")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolenTarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TalentoHumanoId")
                        .HasColumnType("int");

                    b.Property<int>("Tarea")
                        .HasColumnType("int");

                    b.Property<int?>("TareaNavigationTareaId")
                        .HasColumnType("int");

                    b.HasKey("TalentoHumanoTareasId");

                    b.HasIndex("TalentoHumanoId");

                    b.HasIndex("TareaNavigationTareaId");

                    b.ToTable("TalentoHumanoTareas");
                });

            modelBuilder.Entity("Backend.Models.Domain.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TareaId");

                    b.HasIndex("ActividadId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 6, 17, 39, 42, 460, DateTimeKind.Utc).AddTicks(5066),
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            IsActive = true,
                            LastName = "Pérez",
                            PasswordHash = "$2a$11$7Wf.ZNhsxAehoc1oXTD5pOLrww28o17rl1bz1j14ZucOGezfpM6Hm",
                            Provider = "local",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 6, 17, 39, 42, 632, DateTimeKind.Utc).AddTicks(4858),
                            Email = "maria.gonzalez@email.com",
                            FirstName = "María",
                            IsActive = true,
                            LastName = "González",
                            PasswordHash = "$2a$11$lxAOAPDlCCffG1fv92h2u.wcRuyXDbMkZ1UkJgKeEZpa3Sox5BLWW",
                            Provider = "local",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.ActXEntidad", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", "Actividad")
                        .WithMany("ActXEntidades")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Domain.Entidad", "Entidad")
                        .WithMany("ActXEntidades")
                        .HasForeignKey("EntidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("Backend.Models.Domain.Actividad", b =>
                {
                    b.HasOne("Backend.Models.Domain.CadenaDeValor", "CadenaDeValor")
                        .WithMany("Actividades")
                        .HasForeignKey("CadenaDeValorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CadenaDeValor");
                });

            modelBuilder.Entity("Backend.Models.Domain.Administrativos", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("Administrativos")
                        .HasForeignKey("Backend.Models.Domain.Administrativos", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.CadenaDeValor", b =>
                {
                    b.HasOne("Backend.Models.Domain.Objetivo", "Objetivo")
                        .WithMany("CadenasDeValor")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objetivo");
                });

            modelBuilder.Entity("Backend.Models.Domain.CapacitacionEventos", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("CapacitacionEventos")
                        .HasForeignKey("Backend.Models.Domain.CapacitacionEventos", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.CronogramaTarea", b =>
                {
                    b.HasOne("Backend.Models.Domain.Tarea", "Tarea")
                        .WithMany("CronogramaTareas")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("Backend.Models.Domain.Divulgacion", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("Divulgacion")
                        .HasForeignKey("Backend.Models.Domain.Divulgacion", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.EquiposSoftware", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("EquiposSoftware")
                        .HasForeignKey("Backend.Models.Domain.EquiposSoftware", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.GastosViaje", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("GastosViaje")
                        .HasForeignKey("Backend.Models.Domain.GastosViaje", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.Infraestructura", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("Infraestructura")
                        .HasForeignKey("Backend.Models.Domain.Infraestructura", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.MaterialesInsumos", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("MaterialesInsumos")
                        .HasForeignKey("Backend.Models.Domain.MaterialesInsumos", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.Objetivo", b =>
                {
                    b.HasOne("Backend.Models.Domain.Proyecto", "Proyecto")
                        .WithMany("Objetivos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Backend.Models.Domain.Otros", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("Otros")
                        .HasForeignKey("Backend.Models.Domain.Otros", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.ProteccionConocimientoDivulgacion", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("ProteccionConocimientoDivulgacion")
                        .HasForeignKey("Backend.Models.Domain.ProteccionConocimientoDivulgacion", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.Proyecto", b =>
                {
                    b.HasOne("Backend.Models.Domain.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Models.Domain.Recurso", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", "Actividad")
                        .WithMany("Recursos")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Domain.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("EntidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Domain.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Entidad");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("Backend.Models.Domain.RecursoEspecifico", b =>
                {
                    b.HasOne("Backend.Models.Domain.Recurso", "Recurso")
                        .WithMany("RecursosEspecificos")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Backend.Models.Domain.RemuneracionPorAnio", b =>
                {
                    b.HasOne("Backend.Models.Domain.TalentoHumano", "TalentoHumano")
                        .WithMany("Remuneraciones")
                        .HasForeignKey("TalentoHumanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentoHumano");
                });

            modelBuilder.Entity("Backend.Models.Domain.SeguimientoEvaluacion", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("SeguimientoEvaluacion")
                        .HasForeignKey("Backend.Models.Domain.SeguimientoEvaluacion", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.ServiciosTecnologicos", b =>
                {
                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("ServiciosTecnologicos")
                        .HasForeignKey("Backend.Models.Domain.ServiciosTecnologicos", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.TalentoHumano", b =>
                {
                    b.HasOne("Backend.Models.Domain.Contratacion", "Contratacion")
                        .WithMany("TalentosHumanos")
                        .HasForeignKey("ContratacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Domain.RecursoEspecifico", "RecursoEspecifico")
                        .WithOne("TalentoHumano")
                        .HasForeignKey("Backend.Models.Domain.TalentoHumano", "RecursoEspecificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contratacion");

                    b.Navigation("RecursoEspecifico");
                });

            modelBuilder.Entity("Backend.Models.Domain.TalentoHumanoTarea", b =>
                {
                    b.HasOne("Backend.Models.Domain.TalentoHumano", "TalentoHumano")
                        .WithMany("TalentoHumanoTareas")
                        .HasForeignKey("TalentoHumanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Domain.Tarea", "TareaNavigation")
                        .WithMany("TalentoHumanoTareas")
                        .HasForeignKey("TareaNavigationTareaId");

                    b.Navigation("TalentoHumano");

                    b.Navigation("TareaNavigation");
                });

            modelBuilder.Entity("Backend.Models.Domain.Tarea", b =>
                {
                    b.HasOne("Backend.Models.Domain.Actividad", "Actividad")
                        .WithMany("Tareas")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.HasOne("Backend.Models.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Domain.Actividad", b =>
                {
                    b.Navigation("ActXEntidades");

                    b.Navigation("Recursos");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Backend.Models.Domain.CadenaDeValor", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("Backend.Models.Domain.Contratacion", b =>
                {
                    b.Navigation("TalentosHumanos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Entidad", b =>
                {
                    b.Navigation("ActXEntidades");
                });

            modelBuilder.Entity("Backend.Models.Domain.Objetivo", b =>
                {
                    b.Navigation("CadenasDeValor");
                });

            modelBuilder.Entity("Backend.Models.Domain.Proyecto", b =>
                {
                    b.Navigation("Objetivos");
                });

            modelBuilder.Entity("Backend.Models.Domain.Recurso", b =>
                {
                    b.Navigation("RecursosEspecificos");
                });

            modelBuilder.Entity("Backend.Models.Domain.RecursoEspecifico", b =>
                {
                    b.Navigation("Administrativos");

                    b.Navigation("CapacitacionEventos");

                    b.Navigation("Divulgacion");

                    b.Navigation("EquiposSoftware");

                    b.Navigation("GastosViaje");

                    b.Navigation("Infraestructura");

                    b.Navigation("MaterialesInsumos");

                    b.Navigation("Otros");

                    b.Navigation("ProteccionConocimientoDivulgacion");

                    b.Navigation("SeguimientoEvaluacion");

                    b.Navigation("ServiciosTecnologicos");

                    b.Navigation("TalentoHumano");
                });

            modelBuilder.Entity("Backend.Models.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Models.Domain.TalentoHumano", b =>
                {
                    b.Navigation("Remuneraciones");

                    b.Navigation("TalentoHumanoTareas");
                });

            modelBuilder.Entity("Backend.Models.Domain.Tarea", b =>
                {
                    b.Navigation("CronogramaTareas");

                    b.Navigation("TalentoHumanoTareas");
                });
#pragma warning restore 612, 618
        }
    }
}
