// <auto-generated />
using System;
using Backend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 50, 530, DateTimeKind.Utc).AddTicks(372),
                            Description = "Rol con permisos completos del sistema",
                            IsActive = true,
                            Name = "Administrador",
                            Permissions = "[\"users.create\", \"users.read\", \"users.update\", \"users.delete\", \"weather.create\", \"weather.read\", \"weather.update\", \"weather.delete\"]"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 50, 530, DateTimeKind.Utc).AddTicks(382),
                            Description = "Rol con permisos básicos del sistema",
                            IsActive = true,
                            Name = "Usuario",
                            Permissions = "[\"users.read\", \"weather.read\"]"
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("local");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 50, 815, DateTimeKind.Utc).AddTicks(9934),
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            IsActive = true,
                            LastName = "Pérez",
                            PasswordHash = "$2a$11$cixFJpruFhHiSD8j9w0ahOd755T9MGpGEnNmZyqRK30Oi1A2Oi3Hu",
                            Provider = "local",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 124, DateTimeKind.Utc).AddTicks(1009),
                            Email = "maria.gonzalez@email.com",
                            FirstName = "María",
                            IsActive = true,
                            LastName = "González",
                            PasswordHash = "$2a$11$bO9ktC68A/5hSB/ET9EAHeTEszRl6MSxWEabg0ZporEN4JWcKzvEC",
                            Provider = "local",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(7375),
                            Email = "carlos.lopez@email.com",
                            FirstName = "Carlos",
                            IsActive = false,
                            LastName = "López",
                            PasswordHash = "$2a$11$CAjKzAem29lc7.AICC7vS.fiubnfSQdwMQ70ZrHFKUZUXivh7wW7y",
                            Provider = "local",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8156),
                            Date = new DateOnly(2025, 10, 4),
                            Summary = "Bracing",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8191),
                            Date = new DateOnly(2025, 10, 5),
                            Summary = "Warm",
                            TemperatureC = -11
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8196),
                            Date = new DateOnly(2025, 10, 6),
                            Summary = "Chilly",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8200),
                            Date = new DateOnly(2025, 10, 7),
                            Summary = "Warm",
                            TemperatureC = 34
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8204),
                            Date = new DateOnly(2025, 10, 8),
                            Summary = "Hot",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8233),
                            Date = new DateOnly(2025, 10, 9),
                            Summary = "Chilly",
                            TemperatureC = -3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8237),
                            Date = new DateOnly(2025, 10, 10),
                            Summary = "Cool",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8240),
                            Date = new DateOnly(2025, 10, 11),
                            Summary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8244),
                            Date = new DateOnly(2025, 10, 12),
                            Summary = "Freezing",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 4, 1, 59, 51, 431, DateTimeKind.Utc).AddTicks(8250),
                            Date = new DateOnly(2025, 10, 13),
                            Summary = "Warm",
                            TemperatureC = 41
                        });
                });

            modelBuilder.Entity("Backend.Models.Domain.User", b =>
                {
                    b.HasOne("Backend.Models.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
